PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
uv run accelerate launch examples/scripts/dro.py \
  --model_name_or_path Qwen/Qwen3-1.7B \
  --hub_model_id MWilinski/dro-qwen3-1.7b-full-fixed-tau \
  --output_dir /tmp/dro-full-stable-fixed-tau \
  --num_train_epochs 1 \
  --per_device_train_batch_size 32 \
  --gradient_accumulation_steps 1 \
  --learning_rate 2e-5 \
  --tau 1.0 \
  --normalize_rewards True \
  --max_length 1024 \
  --max_prompt_length 512 \
  --eval_strategy steps \
  --eval_steps 2000 \
  --logging_steps 1 \
  --report_to wandb \
  --run_name dro-full-512-q1.7b-stable-fixed-tau \
  --use_peft \
  --lora_r 32 \
  --lora_alpha 16 \
  --lora_dropout 0.05 \
  --lora_target_modules all-linear \
  --dtype bfloat16 \
  --win_rate_num_prompts 256